//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalkafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma_kodlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firma_kodlari()
        {
            this.musteri_gonderileri = new HashSet<musteri_gonderileri>();
        }
    
        public int firma_kodlari_id { get; set; }
        public Nullable<int> firma_id { get; set; }
        public Nullable<int> kod_tipi_id { get; set; }
        public string firma_kod_adi { get; set; }
        public Nullable<int> aktif { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
    
        public virtual firmalar firmalar { get; set; }
        public virtual kod_tipi kod_tipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musteri_gonderileri> musteri_gonderileri { get; set; }
    }
}
