//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalkafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma_odeme_hareketi
    {
        public int firma_odeme_hareketi_id { get; set; }
        public Nullable<int> odeme_miktari_id { get; set; }
        public Nullable<int> firma_id { get; set; }
        public Nullable<System.DateTime> odeme_tarihi { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
    
        public virtual firmalar firmalar { get; set; }
        public virtual odeme_secenekleri odeme_secenekleri { get; set; }
    }
}
