//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalkafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firmalar()
        {
            this.firma_kodlari = new HashSet<firma_kodlari>();
            this.firma_odeme_hareketi = new HashSet<firma_odeme_hareketi>();
        }
    
        public int firma_id { get; set; }
        public string firma_adi { get; set; }
        public string firma_kullaniciadi { get; set; }
        public string firma_sifresi { get; set; }
        public string firma_konumu { get; set; }
        public int aktif { get; set; }
        public System.DateTime kayit_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<firma_kodlari> firma_kodlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<firma_odeme_hareketi> firma_odeme_hareketi { get; set; }
    }
}
