//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalkafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri_gonderileri
    {
        public int musteri_gonderi_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<int> firma_kodlari_id { get; set; }
        public string resim_adres { get; set; }
        public Nullable<int> aktif { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
    
        public virtual firma_kodlari firma_kodlari { get; set; }
        public virtual musteriler musteriler { get; set; }
    }
}
