//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalkafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odeme_secenekleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odeme_secenekleri()
        {
            this.firma_odeme_hareketi = new HashSet<firma_odeme_hareketi>();
        }
    
        public int odeme_miktari_id { get; set; }
        public string odeme_adi { get; set; }
        public Nullable<int> odeme_miktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<firma_odeme_hareketi> firma_odeme_hareketi { get; set; }
    }
}
